### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by amitbatajoo** [yc-huang/Hive-mongo#18]
Hi to all,

Recently I am trying to code in apache river java, and I am testing for user input value from client and process in server and result back to client, but at same time I get the error :

Exception in thread "main" java.lang.NoSuchMethodError: com.sun.jini.example.hel                           lo.Hello.sayHello()Ljava/lang/String;
        at com.sun.jini.example.hello.Client.mainAsSubject(Client.java:142)
        at com.sun.jini.example.hello.Client.main(Client.java:83)

Let me know how to overcome this error and continue my project work.

Thank you all in advance.

**Comment by yc-huang** [comment]
according to the exception message, it's expected there should have a method looks like:
public String sayHello(){...}
in class com.sun.jini.example.hel lo.Hello, but it's not...

What are you trying to build? To me JINI is some dying technology...

**Comment by amitbatajoo** [comment]
i am trying to build a distributed computing service, this is my project work at colz. 
there is a method as you defined: pubilic String sayHello(){....} in class com.sun.jini.example.hel lo.Hello.

**Comment by yc-huang** [comment]
then I guess there might be some older version of this class been cached somewhere. Try to restart everything and try again.
