### ISSUE TITLE
How do I compile?

### ISSUE THREAD

**Issue by MadDataScience** [yc-huang/Hive-mongo#3]
Your readme has great instructions on how to use this once it's built, but unfortunately, no instructions on how to build it. I'm not a Java programmer myself, so a little guidance on this would help a lot. Thank you.

**Comment by yc-huang** [comment]
Hi Alessandro，

Here's a simple guide on how to build, hope it helps:
1. make sure you have java sdk installed (otherwise download and install
from http://www.oracle.com/technetwork/java/index.html) , $JAVA_HOME env
variable is point to the installed directory and $JAVA_HOME/bin/ is
included in $PATH env variable;
1. download maven from http://maven.apache.org and install to a directory
   (let's say $MAVEN_HOME), add $MAVEN_HOME/bin to $PATH
2. git clone Hive-Mongo to a directory; launch a cmd shell, cd that
   directory and execute "mvn package"; if everything is OK, you can find
   "hive-mongo-0.0.1-SNAPSHOT.jar" in the "target" directory.

**Comment by yc-huang** [comment]
attached is the jar file you might try in case you have problem with
building this project.

**Comment by yc-huang** [comment]
The java sdk download link is:
http://www.oracle.com/technetwork/java/javase/downloads/jdk-6u31-download-1501634.html

**Comment by MadDataScience** [comment]
I didn't see any attached jar but I followed your instructions and was able to build hive-mongo-0.0.1-SNAPSHOT.jar
I put it in S3, created an EMR cluster, and loaded it into Hive with
hive> ADD JAR s3://blah.blah.blah/hive-mongo-0.0.1-SNAPSHOT.jar;
I then did:
hive> create external table friend_requests (from_id string, to_id string, state tinyint) 
    >   stored by "org.yong3.hive.mongo.MongoStorageHandler" 
    >   with serdeproperties ( "mongo.column.mapping" = "from_id,to_id,state" ) 
    >   tblproperties ( "mongo.host" = "ec2-XX-XX-XX-XX.us-west-1.compute.amazonaws.com", "mongo.port" = "27017", "mongo.db" = "prod", "mongo.collection" = "friend_requests" );
and got OK.
To see if it worked, I tried:
hive> select \* from friend_requests limit 1;
and got: 
OK
Exception in thread "main" java.lang.NoClassDefFoundError: com/mongodb/MongoException
    at org.yong3.hive.mongo.MongoSplit.getSplits(MongoSplit.java:84)
    at org.yong3.hive.mongo.MongoInputFormat.getSplits(MongoInputFormat.java:83)
    at org.apache.hadoop.hive.ql.exec.FetchOperator.getRecordReader(FetchOperator.java:281)
    at org.apache.hadoop.hive.ql.exec.FetchOperator.getNextRow(FetchOperator.java:320)
    at org.apache.hadoop.hive.ql.exec.FetchTask.fetch(FetchTask.java:133)
    at org.apache.hadoop.hive.ql.Driver.getResults(Driver.java:1114)
    at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:194)
    at org.apache.hadoop.hive.cli.CliDriver.processLineInternal(CliDriver.java:253)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:234)
    at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:487)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:156)
Caused by: java.lang.ClassNotFoundException: com.mongodb.MongoException
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 15 more
and was dropped out of hive. Any idea why?

**Comment by MadDataScience** [comment]
Never mind. I forgot I needed to add mongo-java-driver-2.6.3.jar and guava-r06.jar as well. It works now. Thanks!
