### ISSUE TITLE
Error in metadata: java.lang.NullPointerException 

### ISSUE THREAD

**Issue by JohnOmernik** [yc-huang/Hive-mongo#7]
I am working at testing this, once again thank you for your efforts.  I've compiled all the per the other issue I put in, thanks for that as well.   I have a mongodb running on a different host that is working well I can also connect to it on 27017 from the host running hive. I've created a users collection in the test db.  when I run the following:

create external table mongo_users(id int, name string, age int)
stored by "org.yong3.hive.mongo.MongoStorageHandler"
with serdeproperties ( "mongo.column.mapping" = "_id,name,age" )
tblproperties ( "mongo.host" = "192.166.0.11", "mongo.port" = "27017",
"mongo.db" = "test", "mongo.collection" = "users" );

With Verbose logging turned on, this is the result. Any advice would be welcome. I am running the current version of MongoDB with Hive 0.9. 

hive> create external table mongo_users(id int, name string, age int)
    > stored by "org.yong3.hive.mongo.MongoStorageHandler"
    > with serdeproperties ( "mongo.column.mapping" = "_id,name,age" )
    > tblproperties ( "mongo.host" = "192.168.0.11", "mongo.port" = "27017",
    > "mongo.db" = "test", "mongo.collection" = "users" );
12/10/13 10:51:04 INFO ql.Driver: <PERFLOG method=Driver.run>
12/10/13 10:51:04 INFO ql.Driver: <PERFLOG method=compile>
12/10/13 10:51:04 INFO parse.ParseDriver: Parsing command: create external table mongo_users(id int, name string, age int)
stored by "org.yong3.hive.mongo.MongoStorageHandler"
with serdeproperties ( "mongo.column.mapping" = "_id,name,age" )
tblproperties ( "mongo.host" = "192.168.0.11", "mongo.port" = "27017",
"mongo.db" = "test", "mongo.collection" = "users" )
12/10/13 10:51:04 INFO parse.ParseDriver: Parse Completed
12/10/13 10:51:04 INFO parse.SemanticAnalyzer: Starting Semantic Analysis
12/10/13 10:51:04 INFO parse.SemanticAnalyzer: Creating table mongo_users position=22
12/10/13 10:51:04 INFO ql.Driver: Semantic Analysis Completed
12/10/13 10:51:04 INFO ql.Driver: Returning Hive schema: Schema(fieldSchemas:null, properties:null)
12/10/13 10:51:04 INFO ql.Driver: </PERFLOG method=compile start=1350143464531 end=1350143464687 duration=156>
12/10/13 10:51:04 INFO ql.Driver: <PERFLOG method=Driver.execute>
12/10/13 10:51:04 INFO ql.Driver: Starting command: create external table mongo_users(id int, name string, age int)
stored by "org.yong3.hive.mongo.MongoStorageHandler"
with serdeproperties ( "mongo.column.mapping" = "_id,name,age" )
tblproperties ( "mongo.host" = "192.168.0.11", "mongo.port" = "27017",
"mongo.db" = "test", "mongo.collection" = "users" )
12/10/13 10:51:04 INFO exec.DDLTask: Use StorageHandler-supplied org.yong3.hive.mongo.MongoSerDe for table mongo_users
12/10/13 10:51:04 INFO hive.log: DDL: struct mongo_users { i32 id, string name, i32 age}
FAILED: Error in metadata: java.lang.NullPointerException
12/10/13 10:51:04 ERROR exec.Task: FAILED: Error in metadata: java.lang.NullPointerException
org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.NullPointerException
    at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:544)
    at org.apache.hadoop.hive.ql.exec.DDLTask.createTable(DDLTask.java:3305)
    at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:242)
    at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:134)
    at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:57)
    at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1326)
    at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1118)
    at org.apache.hadoop.hive.ql.Driver.run(Driver.java:951)
    at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:258)
    at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:215)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:406)
    at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:689)
    at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:557)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:197)
Caused by: java.lang.NullPointerException
    at org.apache.hadoop.hive.serde2.objectinspector.StandardStructObjectInspector.init(StandardStructObjectInspector.java:116)
    at org.apache.hadoop.hive.serde2.objectinspector.StandardStructObjectInspector.<init>(StandardStructObjectInspector.java:106)
    at org.apache.hadoop.hive.serde2.objectinspector.ObjectInspectorFactory.getStandardStructObjectInspector(ObjectInspectorFactory.java:274)
    at org.apache.hadoop.hive.serde2.objectinspector.ObjectInspectorFactory.getStandardStructObjectInspector(ObjectInspectorFactory.java:259)
    at org.yong3.hive.mongo.MongoSerDe.initialize(MongoSerDe.java:101)
    at org.apache.hadoop.hive.metastore.MetaStoreUtils.getDeserializer(MetaStoreUtils.java:203)
    at org.apache.hadoop.hive.ql.metadata.Table.getDeserializerFromMetaStore(Table.java:260)
    at org.apache.hadoop.hive.ql.metadata.Table.getDeserializer(Table.java:253)
    at org.apache.hadoop.hive.ql.metadata.Table.getCols(Table.java:490)
    at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:518)
    ... 17 more

FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask
12/10/13 10:51:04 ERROR ql.Driver: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask
12/10/13 10:51:04 INFO ql.Driver: </PERFLOG method=Driver.execute start=1350143464687 end=1350143464745 duration=58>
12/10/13 10:51:04 INFO ql.Driver: <PERFLOG method=releaseLocks>
12/10/13 10:51:04 INFO ql.Driver: </PERFLOG method=releaseLocks start=1350143464745 end=1350143464746 duration=1>

**Comment by JohnOmernik** [comment]
Just an update... I fixed some stuff, but now am getting a similar error:

2012-10-13 11:39:41,106 ERROR ql.Driver (SessionState.java:printError(400)) - FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask

**Comment by JohnOmernik** [comment]
And now with verbose logging:

2012-10-13 11:39:41,106 ERROR ql.Driver (SessionState.java:printError(400)) - FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask
2012-10-13 11:44:47,892 ERROR DataNucleus.Plugin (Log4JLogger.java:error(115)) - Bundle "org.eclipse.jdt.core" requires "org.eclipse.core.resources" but it cannot be resolved.
2012-10-13 11:44:47,900 ERROR DataNucleus.Plugin (Log4JLogger.java:error(115)) - Bundle "org.eclipse.jdt.core" requires "org.eclipse.core.runtime" but it cannot be resolved.
2012-10-13 11:44:47,900 ERROR DataNucleus.Plugin (Log4JLogger.java:error(115)) - Bundle "org.eclipse.jdt.core" requires "org.eclipse.text" but it cannot be resolved.

**Comment by JohnOmernik** [comment]
LOL, more fore all, I did DEBUG logging out...  I am thinking the line 

12/10/13 14:30:13 INFO ql.Driver: Returning Hive schema: Schema(fieldSchemas:null, properties:null)

may be of interest, but I am lost at this point.  

hive> create external table mongo_users(name STRING, age INT)
    > COMMENT 'Ya boy'
    > stored by "org.yong3.hive.mongo.MongoStorageHandler"
    > with serdeproperties ( "mongo.column.mapping" = "name,age" )
    > tblproperties ( "mongo.host"="192.168.0.11","mongo.port"="27017","mongo.db"="test","mongo.collection"="users");
12/10/13 14:30:13 INFO ql.Driver: <PERFLOG method=Driver.run>
12/10/13 14:30:13 INFO ql.Driver: <PERFLOG method=compile>
12/10/13 14:30:13 DEBUG parse.VariableSubstitution: Substitution is on: create external table mongo_users(name STRING, age INT)
COMMENT 'Ya boy'
stored by "org.yong3.hive.mongo.MongoStorageHandler"
with serdeproperties ( "mongo.column.mapping" = "name,age" )
tblproperties ( "mongo.host"="192.168.0.11","mongo.port"="27017","mongo.db"="test","mongo.collection"="users")
12/10/13 14:30:13 INFO parse.ParseDriver: Parsing command: create external table mongo_users(name STRING, age INT)
COMMENT 'Ya boy'
stored by "org.yong3.hive.mongo.MongoStorageHandler"
with serdeproperties ( "mongo.column.mapping" = "name,age" )
tblproperties ( "mongo.host"="192.168.0.11","mongo.port"="27017","mongo.db"="test","mongo.collection"="users")
12/10/13 14:30:13 INFO parse.ParseDriver: Parse Completed
12/10/13 14:30:13 INFO parse.SemanticAnalyzer: Starting Semantic Analysis
12/10/13 14:30:13 INFO parse.SemanticAnalyzer: Creating table mongo_users position=22
12/10/13 14:30:13 INFO ql.Driver: Semantic Analysis Completed
12/10/13 14:30:13 DEBUG parse.SemanticAnalyzer: validation start
12/10/13 14:30:13 INFO ql.Driver: Returning Hive schema: Schema(fieldSchemas:null, properties:null)
12/10/13 14:30:13 INFO ql.Driver: </PERFLOG method=compile start=1350156613478 end=1350156613635 duration=157>
12/10/13 14:30:13 INFO ql.Driver: <PERFLOG method=Driver.execute>
12/10/13 14:30:13 INFO ql.Driver: Starting command: create external table mongo_users(name STRING, age INT)
COMMENT 'Ya boy'
stored by "org.yong3.hive.mongo.MongoStorageHandler"
with serdeproperties ( "mongo.column.mapping" = "name,age" )
tblproperties ( "mongo.host"="192.168.0.11","mongo.port"="27017","mongo.db"="test","mongo.collection"="users")
12/10/13 14:30:13 INFO exec.DDLTask: Use StorageHandler-supplied org.yong3.hive.mongo.MongoSerDe for table mongo_users
12/10/13 14:30:13 INFO hive.log: DDL: struct mongo_users { string name, i32 age}
FAILED: Error in metadata: java.lang.NullPointerException
12/10/13 14:30:13 ERROR exec.Task: FAILED: Error in metadata: java.lang.NullPointerException
org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.NullPointerException
    at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:544)
    at org.apache.hadoop.hive.ql.exec.DDLTask.createTable(DDLTask.java:3305)
    at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:242)
    at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:134)
    at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:57)
    at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1326)
    at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1118)
    at org.apache.hadoop.hive.ql.Driver.run(Driver.java:951)
    at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:258)
    at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:215)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:406)
    at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:689)
    at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:557)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:197)
Caused by: java.lang.NullPointerException
    at org.apache.hadoop.hive.serde2.objectinspector.StandardStructObjectInspector.init(StandardStructObjectInspector.java:116)
    at org.apache.hadoop.hive.serde2.objectinspector.StandardStructObjectInspector.<init>(StandardStructObjectInspector.java:106)
    at org.apache.hadoop.hive.serde2.objectinspector.ObjectInspectorFactory.getStandardStructObjectInspector(ObjectInspectorFactory.java:274)
    at org.apache.hadoop.hive.serde2.objectinspector.ObjectInspectorFactory.getStandardStructObjectInspector(ObjectInspectorFactory.java:259)
    at org.yong3.hive.mongo.MongoSerDe.initialize(MongoSerDe.java:101)
    at org.apache.hadoop.hive.metastore.MetaStoreUtils.getDeserializer(MetaStoreUtils.java:203)
    at org.apache.hadoop.hive.ql.metadata.Table.getDeserializerFromMetaStore(Table.java:260)
    at org.apache.hadoop.hive.ql.metadata.Table.getDeserializer(Table.java:253)
    at org.apache.hadoop.hive.ql.metadata.Table.getCols(Table.java:490)
    at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:518)
    ... 17 more

12/10/13 14:30:13 DEBUG exec.DDLTask: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.NullPointerException
    at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:544)
    at org.apache.hadoop.hive.ql.exec.DDLTask.createTable(DDLTask.java:3305)
    at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:242)
    at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:134)
    at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:57)
    at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1326)
    at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1118)
    at org.apache.hadoop.hive.ql.Driver.run(Driver.java:951)
    at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:258)
    at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:215)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:406)
    at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:689)
    at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:557)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:197)
Caused by: java.lang.NullPointerException
    at org.apache.hadoop.hive.serde2.objectinspector.StandardStructObjectInspector.init(StandardStructObjectInspector.java:116)
    at org.apache.hadoop.hive.serde2.objectinspector.StandardStructObjectInspector.<init>(StandardStructObjectInspector.java:106)
    at org.apache.hadoop.hive.serde2.objectinspector.ObjectInspectorFactory.getStandardStructObjectInspector(ObjectInspectorFactory.java:274)
    at org.apache.hadoop.hive.serde2.objectinspector.ObjectInspectorFactory.getStandardStructObjectInspector(ObjectInspectorFactory.java:259)
    at org.yong3.hive.mongo.MongoSerDe.initialize(MongoSerDe.java:101)
    at org.apache.hadoop.hive.metastore.MetaStoreUtils.getDeserializer(MetaStoreUtils.java:203)
    at org.apache.hadoop.hive.ql.metadata.Table.getDeserializerFromMetaStore(Table.java:260)
    at org.apache.hadoop.hive.ql.metadata.Table.getDeserializer(Table.java:253)
    at org.apache.hadoop.hive.ql.metadata.Table.getCols(Table.java:490)
    at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:518)
    ... 17 more

FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask
12/10/13 14:30:13 ERROR ql.Driver: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask
12/10/13 14:30:13 INFO ql.Driver: </PERFLOG method=Driver.execute start=1350156613636 end=1350156613695 duration=59>
12/10/13 14:30:13 INFO ql.Driver: <PERFLOG method=releaseLocks>
12/10/13 14:30:13 INFO ql.Driver: </PERFLOG method=releaseLocks start=1350156613695 end=1350156613695 duration=0>

**Comment by yc-huang** [comment]
This should be a bug, Please checkout the latest version and have a try, thanks.

**Comment by JohnOmernik** [comment]
YC: Thank you for the update, Here is output now. More verbose of an error, but generally the same.  Thoughts? 

hive (default)> create external table mongo_users(id INT, name STRING, age INT)
              > stored by "org.yong3.hive.mongo.MongoStorageHandler"
              > with serdeproperties ( "mongo.column.mapping" = "_id,name,age" )
              > tblproperties ( "mongo.host"="192.168.0.11","mongo.port"="27017","mongo.db"="test","mongo.collection"="users");
12/10/14 22:05:12 INFO ql.Driver: <PERFLOG method=Driver.run>
12/10/14 22:05:12 INFO ql.Driver: <PERFLOG method=compile>
12/10/14 22:05:12 DEBUG parse.VariableSubstitution: Substitution is on: create external table mongo_users(id INT, name STRING, age INT)
stored by "org.yong3.hive.mongo.MongoStorageHandler"
with serdeproperties ( "mongo.column.mapping" = "_id,name,age" )
tblproperties ( "mongo.host"="192.168.0.11","mongo.port"="27017","mongo.db"="test","mongo.collection"="users")
12/10/14 22:05:12 INFO parse.ParseDriver: Parsing command: create external table mongo_users(id INT, name STRING, age INT)
stored by "org.yong3.hive.mongo.MongoStorageHandler"
with serdeproperties ( "mongo.column.mapping" = "_id,name,age" )
tblproperties ( "mongo.host"="192.168.0.11","mongo.port"="27017","mongo.db"="test","mongo.collection"="users")
12/10/14 22:05:12 INFO parse.ParseDriver: Parse Completed
12/10/14 22:05:13 INFO parse.SemanticAnalyzer: Starting Semantic Analysis
12/10/14 22:05:13 INFO parse.SemanticAnalyzer: Creating table mongo_users position=22
12/10/14 22:05:13 INFO ql.Driver: Semantic Analysis Completed
12/10/14 22:05:13 DEBUG parse.SemanticAnalyzer: validation start
12/10/14 22:05:13 INFO ql.Driver: Returning Hive schema: Schema(fieldSchemas:null, properties:null)
12/10/14 22:05:13 INFO ql.Driver: </PERFLOG method=compile start=1350270312866 end=1350270313030 duration=164>
12/10/14 22:05:13 INFO ql.Driver: <PERFLOG method=Driver.execute>
12/10/14 22:05:13 INFO ql.Driver: Starting command: create external table mongo_users(id INT, name STRING, age INT)
stored by "org.yong3.hive.mongo.MongoStorageHandler"
with serdeproperties ( "mongo.column.mapping" = "_id,name,age" )
tblproperties ( "mongo.host"="192.168.0.11","mongo.port"="27017","mongo.db"="test","mongo.collection"="users")
12/10/14 22:05:13 INFO exec.DDLTask: Use StorageHandler-supplied org.yong3.hive.mongo.MongoSerDe for table mongo_users
12/10/14 22:05:13 INFO hive.log: DDL: struct mongo_users { i32 id, string name, i32 age}
FAILED: Error in metadata: org.apache.hadoop.hive.ql.metadata.HiveException: at least one column must be specified for the table
12/10/14 22:05:13 ERROR exec.Task: FAILED: Error in metadata: org.apache.hadoop.hive.ql.metadata.HiveException: at least one column must be specified for the table
org.apache.hadoop.hive.ql.metadata.HiveException: org.apache.hadoop.hive.ql.metadata.HiveException: at least one column must be specified for the table
    at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:544)
    at org.apache.hadoop.hive.ql.exec.DDLTask.createTable(DDLTask.java:3305)
    at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:242)
    at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:134)
    at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:57)
    at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1326)
    at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1118)
    at org.apache.hadoop.hive.ql.Driver.run(Driver.java:951)
    at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:258)
    at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:215)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:406)
    at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:689)
    at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:557)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:197)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: at least one column must be specified for the table
    at org.apache.hadoop.hive.ql.metadata.Table.checkValidity(Table.java:163)
    at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:522)
    ... 17 more

12/10/14 22:05:13 DEBUG exec.DDLTask: org.apache.hadoop.hive.ql.metadata.HiveException: org.apache.hadoop.hive.ql.metadata.HiveException: at least one column must be specified for the table
    at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:544)
    at org.apache.hadoop.hive.ql.exec.DDLTask.createTable(DDLTask.java:3305)
    at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:242)
    at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:134)
    at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:57)
    at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1326)
    at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1118)
    at org.apache.hadoop.hive.ql.Driver.run(Driver.java:951)
    at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:258)
    at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:215)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:406)
    at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:689)
    at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:557)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:197)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: at least one column must be specified for the table
    at org.apache.hadoop.hive.ql.metadata.Table.checkValidity(Table.java:163)
    at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:522)
    ... 17 more

FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask
12/10/14 22:05:13 ERROR ql.Driver: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask
12/10/14 22:05:13 INFO ql.Driver: </PERFLOG method=Driver.execute start=1350270313030 end=1350270313094 duration=64>
12/10/14 22:05:13 INFO ql.Driver: <PERFLOG method=releaseLocks>
12/10/14 22:05:13 INFO ql.Driver: </PERFLOG method=releaseLocks start=1350270313094 end=1350270313095 duration=1>

**Comment by yc-huang** [comment]
sorry just forget to add the fix... pls try again, and I have include the generated jar in the git repository (maybe not a good idea...), you might try that without build the project.

**Comment by JohnOmernik** [comment]
It works! thanks for looking into it.
