### ISSUE TITLE
Joining to Hive Data? 

### ISSUE THREAD

**Issue by JohnOmernik** [yc-huang/Hive-mongo#8]
Maybe I am assuming to much here, but should we be able to join to Hive Data with out a problem?  I.e. we have a mongo linked table, should I be able to join that data to standard hive table?  Here's a query example:

select h.\* from 
(select mongo_field1, mongo_field2 from mongo_table) m
JOIN
(select hive_field1, hive_field2 from hive table where day = '2012-09-25') h
ON m.mongo_field1 = h.hive_field1 

note: both fields are of STRING type and both subqueries run as intended. Here is the error I get: 
umber of reduce tasks not specified. Estimated from input data size: 1

In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapred.reduce.tasks=<number>
java.lang.ArithmeticException: / by zero
    at org.yong3.hive.mongo.MongoSplit.getSplits(MongoSplit.java:86)
    at org.yong3.hive.mongo.MongoInputFormat.getSplits(MongoInputFormat.java:84)
    at org.apache.hadoop.hive.ql.io.HiveInputFormat.getSplits(HiveInputFormat.java:292)
    at org.apache.hadoop.mapred.JobClient.writeOldSplits(JobClient.java:1044)
    at org.apache.hadoop.mapred.JobClient.writeSplits(JobClient.java:1036)
    at org.apache.hadoop.mapred.JobClient.access$500(JobClient.java:171)
    at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:918)
    at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:869)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1126)
    at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:869)
    at org.apache.hadoop.mapred.JobClient.submitJob(JobClient.java:843)
    at org.apache.hadoop.hive.ql.exec.ExecDriver.execute(ExecDriver.java:435)
    at org.apache.hadoop.hive.ql.exec.MapRedTask.execute(MapRedTask.java:137)
    at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:134)
    at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:57)
    at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1326)
    at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1118)
    at org.apache.hadoop.hive.ql.Driver.run(Driver.java:951)
    at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:258)
    at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:215)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:406)
    at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:689)
    at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:557)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:197)
Job Submission failed with exception 'java.lang.ArithmeticException(/ by zero)'
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.MapRedTask
hive (hive_database)>

**Comment by yc-huang** [comment]
this is a bug; pls try the latest commit, thanks.

**Comment by JohnOmernik** [comment]
Bug is fixed! Great work yc-huang!
